---
#---Configurações Gerais---#

 - name: Alteracao do /etc/profile
   lineinfile: dest=/etc/profile line={{ item }}
   with_items: 
    - '#--- Variaveis e Alias Customizados ---#'
    - 'export HISTTIMEFORMAT="%d/%m/%Y - %H:%M:%S - "'
    - 'export HISTSIZE="5000"'  
    - 'export HISTFILESIZE="5000"'
    - 'alias ls="ls -lh --color"'
    - 'alias grep="grep -i --color"'
    - 'alias vi-"vim"'
    - 'alias rm="rm -i"'  

 - name: Desabilitando SELINUX de forma permanente
   replace:
     dest: /etc/selinux/config
     regexp: 'SELINUX=enforcing'
     replace: 'SELINUX=disabled'
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

 - name: Desabilitando SELINUX de forma temporaria   
   shell: setenforce 0
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

#---Gerenciamento de pacotes e atualização do Sistema Operacional

 - name: Instalação do repositorio epel-release
   yum: name=epel-release state=latest
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
 
 - name: Atualização do sistema operacional
   yum: name=* state=latest update_cache=yes
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

 - name: Instalação de pacotes - RedHat/CentOS
   yum:  name={{common_packages_redhat}} state=latest 
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

 - name: Remocao de  pacotes desnecessarios
   yum: name={{item}} state=absent
   with_items:
     - NetworkManager
     - NetworkManager-libnm
     - firewalld
     - postfix
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

 - name: Atualização do Sistema Operacional
   apt: update_cache=yes upgrade=yes
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
 - name: Atualizacao de versao da distribuicao
   apt: upgrade=dist
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
 - name: Instalacao de pacotes - Debian
   apt:  name={{common_packages_debian}} state=latest update_cache=yes
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

 #---Gerenciamento de usuario---
 
 - name: Criando o usuario 
   user:
     name=ansible
     comment="usuario ansible"
     shell="/bin/bash"
     home="/home/ansible"
     password="senha"

#--- TimeZone

 - name: Configurando o timezone
   file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes owner=root group=root
 
#---Configuracoes de SSH
   
 - name: Configurando sshd_config
   lineinfile:
     dest=/etc/ssh/sshd_config
     state=present
     regexp={{ item.regexp }}
     line={{ item.line }}
   with_items: 
   - { regexp: '#Port 22' , line: 'Port 22' }
   - { regexp: 'XllForwarding yes' , line: 'Xllforwargind no'}

 - name: Definindo protocolo vresao 2 do SSH
   lineinfile: dest=/etc/ssh/sshd_config line='Protocol 2'
 
 - name: Adicionando o motd
   template: src=motd dest=/etc/motd force=yes owner=root group=root mode=0755
   notify:
     - restart SSH     
...
