---
#---Configurações gerais---#

 - name: Ensure Chocolatey installed from internal repo
   win_chocolatey:
    name: chocolatey
    state: present
    source: http://script/url/from/generic/tab/ChocolateyInstall.ps1

...
